### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by Espleth** [jfcostello/AnyBlock-To-Markdown#1]
Hi! You have a step in the installation guide
`pip install -r requirements.txt`
However this file is missing in git

**Comment by jfcostello** [comment]
Yep, this was an oversight on my part, thanks for letting me know!

This tool was part of a larger repo (There's a second part I'm working on to convert the markdown into Tana paste) which had some requirements beyond base Python, but that's no longer the case. I've updated the readme now to remove the unnecessary and confusing requirements.txt instructions and added some basic instructions on how to install Python as this may be useful for a wider, not as tech savvy audience
